flathub-infra/documentation

- docs/02-for-app-authors/06-maintanance.md
Mention, that we also have these on the main website
> Update download stats docs

- docs/02-for-app-authors/02-requirements.md
- docs/02-for-app-authors/05-submission.md
- docs/02-for-app-authors/07-shared-modules.md
> Improve submission steps

- docs/02-for-app-authors/03-appdata-guidelines.md
> Document manifest key

- docs/02-for-app-authors/02-requirements.md
> Be explicit where to define tag and commit

- docs/02-for-app-authors/06-maintanance.md
> Document f-e-d-c options for flathub.json

- docs/02-for-app-authors/05-submission.md
Found a link that leads to 404 page while reading your docs
> Fix broken link

- docs/02-for-app-authors/03-appdata-guidelines/01-quality-guidelines.md
"Icon ratio" is not very descriptive. Footprint is the term we usually use when drawing icons, but open to other suggestions :)
> Quality guidelines: minor header fix

- docs/02-for-app-authors/12-linter.md
> Align footnote links with footnote rendering

- docs/02-for-app-authors/02-requirements.md
> Explain how id and verification interact

- docs/02-for-app-authors/05-submission.md
The gendered language doesn't seem necessary to say what we're trying to say.
> Submission: middlemen → intermediaries

- docs/01-for-users/02-installation.md
Closes #68
@barthalion please have a look
> Describe subsets

- docs/02-for-app-authors/03-appdata-guidelines/01-quality-guidelines.md
Add two new rules for screenshtos:
- Good content
- Up to date
> Quality guidelines: More screenshot rules

- docs/02-for-app-authors/06-maintanance.md
> Explain publishing delay

- docs/02-for-app-authors/02-requirements.md
Closes #27
I'm not sure if it would be sane to do this, so posting here for comments.
> Add example manifest

- docs/02-for-app-authors/10-verification.md
I've been asked by some ISVs and folks internally at Endless what exactly verification is/how it works and I realized it's not as clear as it could be from the docs.
This gets pretty detailed, but I think it can answer most questions people may have about the process, especially considering it took me digging through the Flathub source code itself to answer these questions!
> Verification: add details for verification methods

- docs/02-for-app-authors/10-verification.md
This answers a few questions:
- How can I verify multiple apps?
- Is the code per-domain or per-app?
- Does the code change per-build?
Again based on answering questions for ISVs. As long as I'm here, I corrected "code" to "token" to be more consistent with the copy in the actual verification process.
> verification: Include more info and an example

- docs/02-for-app-authors/03-appdata-guidelines/01-quality-guidelines.mdx
- docs/02-for-app-authors/03-appdata-guidelines/assets/app-icon-grid.svg
- src/css/custom.css
> Add grid and some examples

- docs/01-for-users/07-downgrading.md
Hopefully this makes it a bit easier to follow for people not as experianced.
> Make downgrade docs more accessible

- .github/workflows/deploy.yml
Reverts flathub/documentation#152
> Revert "Bump actions/upload-pages-artifact from 2 to 3"

- .github/workflows/deploy.yml
This reverts commit 5ca8df3d722286c6d8b9e2f4f36f1838e4998d84.
> Revert "Bump actions/deploy-pages from 3 to 4"

- blog/2024-01-08/index.md
Forgot to fix this while editing :)
> Quality blog post: Minor wording fix

- docs/02-for-app-authors/10-verification.md
See https://github.com/flathub/flathub/issues/4855#issue-2077923773
> Fix link on verification page

- docs/02-for-app-authors/03-appdata-guidelines/01-quality-guidelines.md
I was annoyed watching Brodie Robertson's video.
> Update 01-quality-guidelines.md - Small orthographic and gramatical fixes.

- docs/01-for-users/06-verification.md
This can help bridge the two different places we talk about verification
> Verification (for users): link to the docs for developers

- blog/2024-01-30/index.md
We can update the schedule link once the session goes up on the site (and mention the specific track)
> Blog: FOSDEM 2024 post

- docs/02-for-app-authors/03-appdata-guidelines/01-quality-guidelines.md
Everyone seems to be in agreement towards this in the Matrix, so here's the smallest PR ever to these docs.
It adds "(if any)" to the rounded corners mention.
> Added an (if any) to the rounded corners guidelines

- docs/02-for-app-authors/03-appdata-guidelines/01-quality-guidelines.md
This is blocked on the libappstream port, but we'll want it eventually :)
> Quality guidelines: add brand color

- docs/02-for-app-authors/12-linter.md
https://github.com/flathub-infra/flatpak-builder-lint/commit/6a691407675ee0ca94f0b51a2160dde418f14c44 https://github.com/flathub-infra/flatpak-builder-lint/commit/e3def9e5fbbd56fd81aa24f8b61dcc278df06d2b
> linter: Document new errors

- docs/02-for-app-authors/01-why-flathub.md
- docs/02-for-app-authors/05-submission.md
- docs/02-for-app-authors/06-maintenance.md
- docs/02-for-app-authors/10-verification.md
flathub@lists.freedesktop.org doesn't exist
> Use admins AT flathub dot org as the admin email

- docs/03-for-team-members/03-docs-guidelines.md
Probably handy to have a place to write these sort of rules down for consistency. A lot of these are reminders for myself. 😅
> Create documentation guidelines

- docs/02-for-app-authors/06-maintenance.md
Closes https://github.com/flathub-infra/documentation/issues/224
This one is more for transitioning in existing repos.
> Document process for getting write access to app repos

- docs/02-for-app-authors/03-metainfo-guidelines/index.md
- docs/02-for-app-authors/12-linter.md
Mark as command in some places and use the proper casing when not
> Fix usages of appstream

- docs/02-for-app-authors/06-maintenance.md
> maintenance: Mention app teams and change wording a bit

- docs/02-for-app-authors/09-github-actions.md
- docs/02-for-app-authors/12-linter.md
- docs/02-for-app-authors/13-useful-links.md
It is the only working fork now
> docs: Update actions link to flathub-infra

- docs/02-for-app-authors/03-metainfo-guidelines/index.md
https://github.com/ximion/appstream/commit/49ce4910641766026d9bb605b5d13978e946c999 
https://github.com/ximion/appstream/commit/87910461f4c0c70d0502ce3910e4547697315eb8
> metainfo: Clarify developer and name child tags must be present once

- docusaurus.config.js
The json feed is not created otherwise
> Generate all the feeds

- docs/02-for-app-authors/06-maintenance.md
- docs/02-for-app-authors/07-updates.md
- docs/02-for-app-authors/11-external-data-checker.md
> Document automatically submitting app updates

- docs/02-for-app-authors/03-metainfo-guidelines/index.md
> metainfo: Fix license operator

- docs/02-for-app-authors/03-metainfo-guidelines/01-quality-guidelines.md
Adds more guidance for how to choose brand colors, since we had some requests from app developers for this.
> metainfo quality: add more guidance for brand colors

- docusaurus.config.js
- package.json
- plugins/tailwind-plugin.cjs
- src/components/HeroBanner.tsx
- src/css/custom.css
- src/pages/brand-color-preview.tsx
- tailwind.config.js
- yarn.lock
Added tailwind and configuration to enable this
> Add brand color preview page

- docs/02-for-app-authors/03-metainfo-guidelines/index.md
- segement > segment
- seperately > separately
> Fix two typos

- docusaurus.config.js
See https://docusaurus.io/blog/releases/3.2#sitemap-lastmod
> Change to recommended sitemap config

- docs/02-for-app-authors/03-metainfo-guidelines/index.md
> metainfo: Fixed typo

- .yarn/patches/docusaurus-plugin-search-local-npm-2.0.1-4a07fbb27a.patch
- package.json
- yarn.lock
See https://github.com/gabrielcsapo/docusaurus-plugin-search-local/pull/83
> Add patch to fix search

- docs/02-for-app-authors/10-verification.md
- Add comma before but
- Remove comma splice
> Minor grammar improvements

- docs/02-for-app-authors/03-metainfo-guidelines/01-quality-guidelines.md
> Mention window decorations in `up to date`

- blog/2025-02-05/index.md
> blog: Fix 'On the Go' social image

- blog/2025-05-02/index.md
> Vorarbeiter post: fix a couple of typos

- package.json
- yarn.lock
Reverts flathub-infra/documentation#505
> Revert "build(deps): bump swiper from 11.2.10 to 12.0.1"
