flathub-infra/documentation

docs/02-for-app-authors/03-appdata-guidelines.md
This warning is talink about [Kudos](https://gitlab.gnome.org/GNOME/gnome-software/-/blob/8c340ba6922fd0ac9d88f9d5bcbf956b5a46022e/doc/kudos.md). But Kudos are not mentioned in the Docs (as far as I know, they are deprecated), so this Warning is placed in the OARS Section, which is confusing.
=> Remove Kudos Warning

docs/02-for-app-authors/03-appdata-guidelines/01-quality-guidelines.md
Someone on Mastodon pointed out that the previous wording made it seem like the range to shoot for is 35-50, while in reality summaries should be much shorter if at all possible. There's also no point in giving people 50 as an upper limit, because if they don't care enough to make it fit into 35 they won't care to make it fit into 50 either.
=> Quality guidelines: Minor update to summaries

docs/02-for-app-authors/05-submission.md
Sometimes, the requirements link breaks. I suspect that this happens because the web server rewrites urls to contain a trailing slash.
Current behavior: `https://docs.flathub.org/docs/for-app-authors/submission/` -> `https://docs.flathub.org/docs/for-app-authors/submission/requirements`
Intended behavior: `https://docs.flathub.org/docs/for-app-authors/submission` -> `https://docs.flathub.org/docs/for-app-authors/requirements`
=> Fix broken link

docs/02-for-app-authors/03-appdata-guidelines/index.md
I understand the noun is spelled "licence" in UK-English; however, since the AppData documentation, linked SPDX page, and metainfo tags themselves all spell it "license" as in US-English, it seems like we should be consistent.
=> AppData Guidelines: licence → license

docs/02-for-app-authors/09-verification.md
This is useful documentation for when a third-party/community member has uploaded an app, and then the original developer wants to get it verified; we need to point them to how to gain ownership as a first step.
=> authors/verification: mention how to verify an existing app

docs/02-for-app-authors/03-appdata-guidelines/01-quality-guidelines.md
There are quiet a few apps, with only one view, where multiple sceenshots would be a bad idea.
=> Relax rule to allow apps with one screenshot

docs/02-for-app-authors/02-requirements.md
Hopefully prevents the situation with Kaiteki. The app id was `moe.craftplacer.kaiteki` 2 years ago https://github.com/Kaiteki-Fedi/Kaiteki/commit/356d9e865bb7b6a594ffb14bc5558e90e73f4929 but was submitted under a different app-id  `app.kaiteki.Kaiteki` leading to https://github.com/flathub/app.kaiteki.Kaiteki/issues/3
The submitters should ensure everything is consistent, it's hard to go look at source code of every application for possible mismatches while reviewing. 
This isn't mentioned in https://docs.flatpak.org/en/latest/conventions.html#application-ids or anywhere else. It's hinted at the session-bus policy section of the flatpak docs.
This isn't a hard requirement (hence "should") as applications like Firefox, Thunderbird etc. don't follow the dbus spec for naming the app id and …
=> Clarify that app-id used in manifest should match with upstream

README.md, docs/02-for-app-authors/02-requirements.md
Merge after https://github.com/flatpak/flatpak-docs/pull/415, the link should work after that is deployed
=> Tweak wording of app-id requirement and link to flatpak-docs

docs/02-for-app-authors/03-appdata-guidelines/01-quality-guidelines.md
Only image or video does.
Also provide a full example
https://freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-screenshots
=> Screenshot tag doesn't support xml:lang as per spec

docs/02-for-app-authors/03-appdata-guidelines/01-quality-guidelines.md
Intended to address cases like [this](https://flathub.org/apps/org.wesnoth.Wesnoth), where the icon is well-executed but stylistically very different from modern icons. In these cases we can do what iOS/Android do, and have a buttonized cropped square/circle.
=> Quality guidelines: add paragrah about unique icon styles

docs/02-for-app-authors/12-linter.md
Dropped in https://github.com/flathub/flatpak-builder-lint/commit/aae87815476d5797f42dcf5d876c4568b024a9e7
=> Drop KDE tray linter error

docs/02-for-app-authors/06-maintenance.md
This PR fixes the invalid link to [submission page](https://docs.flathub.org/docs/for-app-authors/submission/) in docs to correctly point to the new page path.
The fix follows the format of other links in the docs which work correctly, such as the requirements link in the first paragraph of [`Before submission`](https://github.com/flathub-infra/documentation/blob/main/docs/02-for-app-authors/05-submission.md#before-submission) in submission page. 
The PR needs testing. I did not set up the development environment to test the change.
=> Fix link to submission page in docs

blog/2024-01-08/index.md
There has been raised concerns about the post linking solely to a GNOME-centric room as a source of app icon design help. While this has turned out to be due to the room being the only known practical resource at the time of writing the article, it would be good to bring other platforms more visibly into it to make it 100% clear that this is an initiative for all communities with apps on Flathub, and not just GNOME. The KDE VDG room is a catchall for KDE design stuff, so let's give KDE app developers somewhere to go too. I have asked the KDE folks, and they are ok with this.
=> add link to KDE VDG room

docs/02-for-app-authors/03-appdata-guidelines/01-quality-guidelines.md
There was a lot of negatives happening (you don't have to follow these, but if you don't, we won't promote your app). This attempts to keep the same meaning but clean up the copy for clarity a bit—and focuses on highlighting the benefits a bit more.
=> Quality guidelines: clarify opening a bit

docs/02-for-app-authors/02-requirements.md
Current link goes to https://docs.flathub.org/docs/for-app-authors/requirements/shared-modules while the right one is https://docs.flathub.org/docs/for-app-authors/shared-modules
=> Fix link to shared modules

blog/2024-01-08/index.md
Cherry-picked as requested from #188
Adds a summary and truncate tag to the top of the Metadata Guidelines post so it doesn't spit the whole post out on the index (important as we start writing more posts).
In general, we should format posts this way with a one-paragraph intro at the top that acts as a summary to get people to click through to read.
I also fixed one typo (`highlight`) and added whitespace beneath headings for authoring legibility (doesn't affect the presentation).
=> Metadata Guidelines post: summarize and truncate for index

docs/02-for-app-authors/03-appdata-guidelines/01-quality-guidelines.md
Keeps the same intent, but:
- Adds an example to clarify when an app name can include an edition (e.g. `Discord Canary` or `Plex HTPC`) based on feedback
_I don't actually love the `Plex HTPC` example, but that's what Plex uses as their name for the distinct home theater version of the app (which is designed to be driven with a remote on a TV, not a mouse and keyboard on a desktop). I'm open to another example; the ones mentioned to me were `Discord Canary` but it's not public-facing, and `Firefox ESR` but that's not on Flathub, so… 🤷🏻_
- Minor cleanups for concision
- Clarify where formatting is part of _an established_ brand; someone pointed out the app name is the brand so this exemption makes no sense unless we qualify it a bit
=> Quality guidelines: clarify app name section

blog/2024-01-25/index.md
Annoyingly, the path actually being used on the live site is relative to the base URL, not the post URL: `https://docs.flathub.org/milestones.png`
Maybe it needs to be explicitly relative (e.g. `./milestones.png`, if I'm reading [this issue](https://github.com/facebook/docusaurus/issues/6718) correctly? Otherwise I guess we'd either need to put the `milestones.png` image somewhere in `static/img/` or include the full URL (with hash) here.
=> Blog: set explicitly-relative path for image

docs/02-for-app-authors/02-requirements.md, docs/02-for-app-authors/03-appdata-guidelines/index.md
And also serve as a template for all the tags necessary to pass validation and Flathub guidelines.
The spec is way too verbose and provides too many options, so people get easily lost. This can be easily used as a template and also while reviewing for linking purposes.
I removed a bunch of legacy stuff like notes about `.desktop` appids etc. which is not allowed anymore in the linter https://docs.flathub.org/docs/for-app-authors/linter#appid-ends-with-lowercase-desktop, replaced "should" with "must" wherever necessary and remove some notes.
=> Refactor appdata guidelines to provide more examples

docs/02-for-app-authors/12-linter.md
https://github.com/flathub-infra/flatpak-builder-lint/commit/5159397908144200fef93c2910cb0be71cdd11f4
=> Document no-exportable-icon-installed error from linter

docs/02-for-app-authors/03-appdata-guidelines/index.md
Recommend using vcs-browser URL for open source projects.
=> Add vcs-browser URL type to appdata guidelines

docs/02-for-app-authors/03-appdata-guidelines/index.md
Closes https://github.com/flathub-infra/documentation/issues/22
- branching is covered in maintenance docs
- flathub.json is now obsolete since I removed those from the linter
So only the note about appdata is necessary.
Everything else is not specific to Flathub and/or is already covered.
=> Add a section about extension metainfo file

docs/02-for-app-authors/03-metainfo-guidelines/01-quality-guidelines.md
Everything in https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html is covered in the Metainfo guidelines page along with the places where Flathub diverges.
The whole part about screenshots is documented in the quality guidelines page.
=> quality-guidelines: Link Flathub's metainfo guidelines quickstart page

docs/02-for-app-authors/12-linter.md
See https://github.com/flathub-infra/flatpak-builder-lint/commit/96c0ed820ebea0fb4c75c3b83aaaeb10005436fa
=> linter: Document metainfo-missing-component-tag error

docs/02-for-app-authors/03-metainfo-guidelines/index.md
Also explicitly mention that description has to be translated by each `<p>` and `<li>` tags
=> metainfo: Provide an untranslated list item in description

docs/02-for-app-authors/06-maintenance.md
If the extension point is defined in runtime and it is set to auto install on certain conditions a EOL message will appear on whenever said runtime is installed and pulls in the extension as a dependency ie. on every app install
=> maintenance: Add a note to not EOL extensions or baseapps

docs/02-for-app-authors/05-submission.md
This fixes a problem with the instructions.
If you follow them as stated (as I did), when you go to build the manifest, you will get an error:
error: No remote refs found for ‘flathub’
Error installing deps: running `flatpak --user install -y --noninteractive flathub org.kde.Sdk/x86_64/5.15-23.08`: Child process exited with code 1
The repo already was added system wide, and adding it again did not change the error.
Adding the repo with the --user flag allowed the build command to continue.
=> Update 05-submission.md to add missing command

docs/02-for-app-authors/03-metainfo-guidelines/01-quality-guidelines.md
I think it would be nice to require default accent colors in screenshots now that they're configurable cross-desktop, to keep some degree of consistency across screenshots and make it clear which apps actually have an overriden accent color. The default is blue for both KDE and GNOME (and elementaryOS if I'm not wrong), so it should be pretty easy to mandate.
/cc @bertob @cassidyjames
=> quality guidelines: Mention accent colors

docusaurus.config.js
Should fix #393 but I wanna make sure that's the right way to edit the config before merging.
=> Config: add `rel=me` to verify Mastodon account

docs/02-for-app-authors/03-metainfo-guidelines/index.md
I think this is necessary, right? I couldn't get `--datapath` to work at all (I think that's a me problem), so I couldn't test it.
=> metainfo: Include ID in appstreamcli get command

blog/2025-02-21/index.md
I had feedback on some of the changes suggested to my post, but didn't get a chance to review it before I went to bed. In general I was happy with the sentiment—thanks @sonnyp. I did revert and recondense a little bit of it for flow and to keep the focus largely on safety and the journey from start to finish (e.g. without mentioning human review until the human review section).
Hard wrapping drives me a bit nuts for long-form content because it causes reformatting of many lines when even small amounts of copy change, but I've left it in the sections that were touched. In general, soft wrapping plus the inline diff on GitHub does a good job of highlighting changes without causing more noise and reflowing.
Thanks again everyone for the reviews and improvements!
=> Safety post: iterate to recondense/improve flow

src/pages/banner-preview.tsx
From https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-screenshots
> Images should ideally be provided in the PNG format; using JPEG or WebP is also permitted for images in metainfo files.
=> Allow JPEG and WebP images as Screenshot in the Banner Preview
